/**
 * Teams2Teams API prototype
 * This is a simple API in case of try the login functions out.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ErrorMessage model module.
 * @module model/ErrorMessage
 * @version 1.0.0
 */
class ErrorMessage {
    /**
     * Constructs a new <code>ErrorMessage</code>.
     * @alias module:model/ErrorMessage
     * @param errorCode {Number} 
     * @param errorMessage {String} 
     */
    constructor(errorCode, errorMessage) { 
        
        ErrorMessage.initialize(this, errorCode, errorMessage);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, errorCode, errorMessage) { 
        obj['error_code'] = errorCode;
        obj['error_message'] = errorMessage;
    }

    /**
     * Constructs a <code>ErrorMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ErrorMessage} obj Optional instance to populate.
     * @return {module:model/ErrorMessage} The populated <code>ErrorMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorMessage();

            if (data.hasOwnProperty('error_code')) {
                obj['error_code'] = ApiClient.convertToType(data['error_code'], 'Number');
            }
            if (data.hasOwnProperty('error_message')) {
                obj['error_message'] = ApiClient.convertToType(data['error_message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} error_code
 */
ErrorMessage.prototype['error_code'] = undefined;

/**
 * @member {String} error_message
 */
ErrorMessage.prototype['error_message'] = undefined;






export default ErrorMessage;

