/**
 * Teams2Teams API prototype
 * This is a simple API in case of try the login functions out.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoginOutput model module.
 * @module model/LoginOutput
 * @version 1.0.0
 */
class LoginOutput {
    /**
     * Constructs a new <code>LoginOutput</code>.
     * @alias module:model/LoginOutput
     */
    constructor() { 
        
        LoginOutput.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LoginOutput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoginOutput} obj Optional instance to populate.
     * @return {module:model/LoginOutput} The populated <code>LoginOutput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoginOutput();

            if (data.hasOwnProperty('sessionId')) {
                obj['sessionId'] = ApiClient.convertToType(data['sessionId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} sessionId
 */
LoginOutput.prototype['sessionId'] = undefined;






export default LoginOutput;

