/**
 * Teams2Teams API prototype
 * This is a simple API in case of try the login functions out.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Pong model module.
 * @module model/Pong
 * @version 1.0.0
 */
class Pong {
    /**
     * Constructs a new <code>Pong</code>.
     * @alias module:model/Pong
     * @param pong {String} 
     */
    constructor(pong) { 
        
        Pong.initialize(this, pong);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pong) { 
        obj['pong'] = pong;
    }

    /**
     * Constructs a <code>Pong</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Pong} obj Optional instance to populate.
     * @return {module:model/Pong} The populated <code>Pong</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Pong();

            if (data.hasOwnProperty('pong')) {
                obj['pong'] = ApiClient.convertToType(data['pong'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} pong
 */
Pong.prototype['pong'] = undefined;






export default Pong;

