/**
 * Teams2Teams API prototype
 * This is a simple API in case of try the login functions out.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Teams2TeamsApiPrototype);
  }
}(this, function(expect, Teams2TeamsApiPrototype) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Teams2TeamsApiPrototype.RegistrationData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RegistrationData', function() {
    it('should create an instance of RegistrationData', function() {
      // uncomment below and update the code to test RegistrationData
      //var instane = new Teams2TeamsApiPrototype.RegistrationData();
      //expect(instance).to.be.a(Teams2TeamsApiPrototype.RegistrationData);
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new Teams2TeamsApiPrototype.RegistrationData();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instane = new Teams2TeamsApiPrototype.RegistrationData();
      //expect(instance).to.be();
    });

  });

}));
